[package]
name = "pincon-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.114", features = ["extra-traits"] }
quote = "1.0.44"
pinocchio = { workspace = true }

[lib]
proc-macro = true
