[package]
name = "basic-usage"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pincon = { path = "../.." }
pinocchio = { version = "0.10.1" }
pinocchio-log = { version = "0.5.1" }
